### ISSUE TITLE
Query engine is unstable under load

### ISSUE THREAD

**Issue by assertnotnull** [prisma/prisma-engines#1498]
We have been facing latency problems with prisma and it seems to come from the query engine. We use K8S readiness and liveness probes to restart the pods or mark it as not ready to receive connections and here is the amount we have since. Here are the amount of times it was triggered on a single pod.

![image](https://user-images.githubusercontent.com/821567/103826749-69078c80-5045-11eb-908c-d3bf538217ca.png)

We use this in the healthz endpoint:

```
  server.get('/healthz', (req, res) => {
    const timeout = new Promise((resolve, reject) => {
      setTimeout(() => {
        reject()
      }, Number.parseInt(process.env.DATABASE_CONNECTION_TIMEOUT || '20000'))
    })
    Promise.race([timeout, prismaClient.$connect()])
      .then(() => {
        return prismaClient.$queryRaw('select now()')
      })
      .then(() => {
        res.sendStatus(200)
      })
      .catch(() => {
        res.sendStatus(503)
      })
  })
```

Here's the K8S values we use (app takes 40 sec until it's ready to receive requests):
```
readinessProbe:
  initialDelaySeconds: 40
  httpGet:
    path: /healthz
    port: 5000
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 20
  failureThreshold: 5
  httpGet:
    path: /healthz
    port: 5000

```
Doing this save our clients long requests (prior to this, the average latency was pretty high and sometimes can bust the default 60s timeout)

Here's our graph when I deployed the change with readiness probe active

![image](https://user-images.githubusercontent.com/821567/103915239-f516c400-50d8-11eb-875d-fb5fef9dbd24.png)

Unfortunately the query engine is like a black box..
